### PR TITLE
add multiple domain support

### PR DESCRIPTION
**Pull request by PoshAJ**
Added support for situations with multiple domains such as children domains. This had the side effect of removing the requirement for the ActiveDirectory module.

### CODE REVIEW

**Review by santisq — COMMENTED** [review]
@PoshAJ I made a few changes to the source code. Removed `anr` filter too. Testing it on my side looks good, could you please test it on yours and let me know if it's working properly? If you have some tests groups and are willing to update the old screenshots feel free to do so. Thank you.

**Comment by PoshAJ** [comment]
> @PoshAJ I made a few changes to the source code. Removed `anr` filter too. Testing it on my side looks good, could you please test it on yours and let me know if it's working properly? If you have some tests groups and are willing to update the old screenshots feel free to do so. Thank you.

Confirmed changes work with multiple domains, will take updated screenshots for README.md. One thing of note is that now that it's cross domain, would we want to add that to the output? I.E DOMAIN\USER vice just USER.

**Comment by santisq** [comment]
> > @PoshAJ I made a few changes to the source code. Removed `anr` filter too. Testing it on my side looks good, could you please test it on yours and let me know if it's working properly? If you have some tests groups and are willing to update the old screenshots feel free to do so. Thank you.
> 
> Confirmed changes work with multiple domains, will take updated screenshots for README.md.
> 
> @santisq One thing of note is that now that it's cross domain, would we want to add that to the output? I.E DOMAIN\USER vice just USER.

@PoshAJ Sounds good, you can add that change if you like then merge. I'll probably rewrite this function as a binary cmdlet later this week. The code is really old and needs improvement but definitely if you come up with more improvements make a new PR. I'm thinking I'll add a `-Properties` parameter too. Thanks.

**Comment by santisq** [comment]
looking good. thank you for your contribution @PoshAJ

**Comment by PoshAJ** [comment]
> looking good. thank you for your contribution @PoshAJ

@santisq Not a problem :) if you need/want a collaborator for the rewrite, let me know.

**Pull request merged**
